"""Add timezone field to user table

Revision ID: 7d6276101286
Revises: 0395b08a3fb3
Create Date: 2025-08-16 15:05:35.530200

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '7d6276101286'
down_revision = '0395b08a3fb3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Add timezone column as nullable first
    op.add_column('user', sa.Column('timezone', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True))
    
    # Update existing users to have UTC timezone
    op.execute("UPDATE \"user\" SET timezone = 'UTC' WHERE timezone IS NULL")
    
    # Now make the column non-nullable
    op.alter_column('user', 'timezone', nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'timezone')
    # ### end Alembic commands ###
