"""Add habit logs and streak cache tables

Revision ID: a1b2c3d4e5f6
Revises: 07e713565f33
Create Date: 2025-08-16 16:00:00.000000

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a1b2c3d4e5f6'
down_revision = '07e713565f33'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Create habit_logs table
    op.create_table('habit_logs',
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.Column('id', sa.Uuid(), nullable=False),
        sa.Column('habit_id', sa.Uuid(), nullable=False),
        sa.Column('user_id', sa.Uuid(), nullable=False),
        sa.Column('local_date', sa.Date(), nullable=False),
        sa.Column('recorded_at', sa.DateTime(), nullable=False),
        sa.Column('idempotency_key', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
        sa.Column('meta', sa.JSON(), nullable=True),
        sa.ForeignKeyConstraint(['habit_id'], ['habit.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('habit_id', 'local_date', name='uq_habit_logs_habit_id_local_date')
    )
    
    # Create indexes for habit_logs
    op.create_index('ix_habit_logs_local_date', 'habit_logs', ['local_date'])
    op.create_index('ix_habit_logs_habit_id', 'habit_logs', ['habit_id'])
    op.create_index('ix_habit_logs_user_id', 'habit_logs', ['user_id'])
    
    # Create streaks_cache table
    op.create_table('streaks_cache',
        sa.Column('habit_id', sa.Uuid(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.Column('current_streak', sa.Integer(), nullable=False),
        sa.Column('longest_streak', sa.Integer(), nullable=False),
        sa.Column('last_updated', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(['habit_id'], ['habit.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('habit_id')
    )
    
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('streaks_cache')
    op.drop_index('ix_habit_logs_user_id', table_name='habit_logs')
    op.drop_index('ix_habit_logs_habit_id', table_name='habit_logs')
    op.drop_index('ix_habit_logs_local_date', table_name='habit_logs')
    op.drop_table('habit_logs')
    # ### end Alembic commands ###